title: Hello Blog
author: @imincheol
email: imincheol@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog was created by 2021.10.03 via Github LearningLab  

# social links
twitter_username: Lucablaq
github_username:  imincheol

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
